# Welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0, 1]

np.int64(6)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

# Array creation: Conversion from other Python structure

In [6]:
listarray = np.array([[1,2,3] , [5,8,5] , [0,3,1]])

In [7]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [11]:
zeros = np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng = np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
lspace = np.linspace(1,50,10)

In [16]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
one = np.array([1,3,4,634,2])

In [18]:
one.argmax()

np.int64(3)

In [19]:
one.argmin()

np.int64(0)

In [20]:
one.argsort()

array([0, 4, 1, 2, 3])

In [25]:
ar1 = np.array([[1,2,2],
               [4,2,1],
               [10,5,4]])

In [26]:
ar2 = np.array([[2,3,1],
               [3,5,6],
               [9,4,2]])

In [27]:
ar1 + ar2

array([[ 3,  5,  3],
       [ 7,  7,  7],
       [19,  9,  6]])

In [28]:
[32,34] + [24,26] 

[32, 34, 24, 26]

In [29]:
 ar1 * ar2

array([[ 2,  6,  2],
       [12, 10,  6],
       [90, 20,  8]])

In [31]:
np.sqrt(ar1)

array([[1.        , 1.41421356, 1.41421356],
       [2.        , 1.41421356, 1.        ],
       [3.16227766, 2.23606798, 2.        ]])

In [32]:
ar1.sum()

np.int64(31)

In [33]:
ar1.min()

np.int64(1)

In [34]:
ar1.max()

np.int64(10)

In [37]:
type(np.where(ar1>5))

tuple

In [39]:
np.count_nonzero(ar1)

9

In [41]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [45]:
ar1[1,2] = 0

In [46]:
np.nonzero(ar1)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))

In [47]:
import sys

In [49]:
py_ar = [0,4,55,2]

In [50]:
np_ar = np.array(py_ar)

In [51]:
sys.getsizeof(1) * len(py_ar)

112

In [1]:
np_ar1.itemsize * np_ar1.size

NameError: name 'np_ar1' is not defined